spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/testJPA
    username: postgres
    password: LQHpostgres2309!
  jpa:
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  brevo:
    api-key: ${BREVO_API_KEY}
    from-email: lequanghung.work@gmail.com
    template-id-email-verification: 2
    verificationLink: http://localhost:8080/user/confirm-email
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    title: Backend Service
    version: 1.0.0
    server: http://localhost:${server.port}

jwt:
  secretKey: abc@123
